const cubes = [
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ],
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ],
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ],
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ],
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ],
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ],
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ],
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ],
    [
        { id: 0, value: '', isValid: false },
        { id: 1, value: '', isValid: false },
        { id: 2, value: '', isValid: false },
        { id: 3, value: '', isValid: false },
        { id: 4, value: '', isValid: false },
        { id: 5, value: '', isValid: false },
        { id: 6, value: '', isValid: false },
        { id: 7, value: '', isValid: false },
        { id: 8, value: '', isValid: false },
    ]
]

export default cubes;